---
name: NewsUI
author: Eforce, Lime
api: [3.0.0, 4.0.0]
description: "NewsUI plugin"
main: News\Main
version: 1.0.0
load: STARTUP

commands:
 news:
 description: reads the article for today

---